# Generated by Django 3.0.5 on 2021-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classs',
        ),
        migrations.AddField(
            model_name='student',
            name='classs',
            field=models.ManyToManyField(blank=True, to='school.Classe'),
        ),
    ]
